version: "3"

networks:
  proxy:
    external: true

services:
  backend:
    build: ./app
    restart: unless-stopped
    environment:
      MY_NICE_PASSWORD: test
    labels:
      # Traefik configuration, Hostname needs to be changed
      - traefik.http.routers.backend-http.rule=Host(`api.marc-schulz.org`)
      - traefik.http.routers.backend-http.entrypoints=http
      - traefik.http.routers.backend-http.middlewares=redirect
      - traefik.http.routers.backend-https.rule=Host(`api.marc-schulz.org`)
      - traefik.http.routers.backend-https.entrypoints=https
      - traefik.http.routers.backend-https.tls=true
      - traefik.http.routers.backend-https.tls.certresolver=letsencrypt
      - traefik.http.services.backend.loadbalancer.server.port=8000
      - traefik.http.middlewares.redirect.redirectscheme.scheme=https
    networks:
      - proxy