version: "3"

networks:
  web:
    external: true

services:
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /data/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /data/caddy/data:/data
      - /data/caddy/config:/config
    networks:
      - web

  backend:
    build: ./app
    restart: unless-stopped
    ports:
      - 8000:8000
    environment:
      MY_NICE_PASSWORD: test
    networks:
      - web
      
  frontend:
    build: ./frondend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - HOST=0.0.0.0
    networks:
      - web
    depends_on:
      - backend