version: "3"
services:
  backend:
    build: ./app
    restart: unless-stopped
    ports:
      - 8000:8000
    networks:
      - "demo-net"
      
  frontend:
    build: ./frondend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - HOST=0.0.0.0
    networks:
      - "demo-net"
    depends_on:
      - backend
networks:
  demo-net: